name: Test Code

on:
  pull_request:
  push:
    branches:
      - develop/*

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Test Lint
        run: npm run lint

      - name: Test coverage
        run: npm run test

      - name: Use action
        id: get-branch
        uses: ypicard/get-branch-name-github-action@v1

      - name: Display formated branch name
        run: echo ${{ steps.get-branch.outputs.branch }} | sed 's/^[^\/]\+\///'

      - name: Set env
        run: echo "My_Branch=$(echo ${{ steps.get-branch.outputs.branch }} | sed 's/^[^\/]\+\///')" >> $GITHUB_ENV

      - name: get env name
        run: echo $My_Branch

      - name: Create PR
        uses: medlypharmacy/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ My_Branch }}
          BASE_BRANCH: main
