name: Deploy to QA env

on:
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
env:
  CI: false
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  QA-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build

      # - name: Run test
      #   run: npm run test

      # Sets the branch name as environment variable
      - uses: nelonoel/branch-name@v1.0.1
      - name: deploy to netlify
        id: deploy-netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: TvSn2ki9oV2tPk5OsOSbLa3WIaHzpBx9UFbiXg94FaI
          NETLIFY_SITE_ID: 5b9c80b4-ce4b-44a7-b2f1-287f78253288

        # Creates a status check with link to preview
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
      - name: print url
        run: echo ${{ steps.deploy-netlify.outputs.NETLIFY_LIVE_URL }}
