name: Deploy to QA env

on:
  pull_request:
  push:
    branches-ignore:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#Sets environment var CI to false to prevent error from warnings
env:
  CI: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Validate-Dev-Changes:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "16"

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Test Lint
  #       run: npm run lint

  #     - name: Test coverage
  #       run: npm run test

  QA-deploy:
    # needs: Validate-Dev-Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      # - name: Run test
      #   run: npm run test

      - name: Set Homepage
        run: npm run setHomepage

      - name: Build
        run: CI=false npm run build

      - name: deploy to QA env --> Netlify
        environment:
          name: QA
        run: netlify deploy --prod --auth ${{ secrets.NETLIFY_TOKEN }} --site ${{ secrets.SITE_ID }}

  PR-Management:
    needs: QA-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Use action
        id: get-branch
        uses: ypicard/get-branch-name-github-action@v1

      - name: Create PR
        uses: medlypharmacy/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ steps.get-branch.outputs.branch }}
          BASE_BRANCH: main
